import { Metadata } from 'next'
import React, { ReactNode } from 'react'
import SidePanel from '@/components/SidePanel'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const AppLayout = ({ children }: { children: ReactNode }) => {
  return (
    <div className="flex bg-gray-100 min-h-screen">
      <SidePanel />
      <div className="flex flex-1 flex-col py-15 px-10 bg-gray-100">
        {children}
      </div>
    </div>
  )
}

export default AppLayout
