import { LoginProvider } from '@/features/auth/contexts/LoginContext'
import { Metadata } from 'next'
import React, { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const LoginLayout = ({ children }: { children: ReactNode }) => {
  return <LoginProvider>{children}</LoginProvider>
}

export default LoginLayout
