import { SignUpProvider } from '@/features/auth/contexts/SignUpContext'
import { Metadata } from 'next'
import React, { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const AppLayout = ({ children }: { children: ReactNode }) => {
  return (
    <SignUpProvider>
      <div className="flex h-screen w-screen flex-col items-center justify-center">
        {children}
      </div>
    </SignUpProvider>
  )
}

export default AppLayout
