import { Metadata } from 'next'
import React, { ReactNode } from 'react'
import { ModalProvider } from '@/features/incomes/contexts/ModalContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const IncomesLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <ModalProvider>{children}</ModalProvider>
    </>
  )
}

export default IncomesLayout
