import { Metadata } from 'next'
import React, { ReactNode } from 'react'
import { TransactionModalProvider } from '@/contexts/TransactionModalContext'
import { CategoryType } from '@/types/CategoryType'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const categoryList: CategoryType[] = [
  {
    id: 1,
    name: '給与',
  },
  {
    id: 2,
    name: '副業',
  },
  {
    id: 3,
    name: 'ボーナス',
  },
  {
    id: 4,
    name: '投資',
  },
]
const IncomesLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <TransactionModalProvider
        transactionType="incomes"
        categoryList={categoryList}
      >
        {children}
      </TransactionModalProvider>
    </>
  )
}

export default IncomesLayout
