import { SignUpProvider } from '@/features/auth/contexts/SignUpContext'
import { Metadata } from 'next'
import React, { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const SignUpLayout = ({ children }: { children: ReactNode }) => {
  return <SignUpProvider>{children}</SignUpProvider>
}

export default SignUpLayout
